<?php
// BDMovieHub - AJAX endpoint to report a broken video
require_once __DIR__ . '/config.php';

while (ob_get_level() > 0) { ob_end_clean(); }
header('Content-Type: application/json; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(array('success' => false, 'error' => 'POST required'));
    exit;
}

/* ---------- CSRF check (session-based token) ----------
 * The report form embeds a hidden "csrf" field generated by csrfField().
 * Anonymous visitors get a session on first page load (config.php starts it),
 * so the token is available when the form is rendered.
 */
if (!verifyCsrf()) {
    echo json_encode(array('success' => false, 'error' => 'Security token expired. Please refresh the page and try again.'));
    exit;
}

/* ---------- Simple IP-based rate limit (max 5 reports / 10 minutes) ---------- */
define('FILE_REPORT_RATE', DATA_DIR . '/report_rate.json');
$__ip = clientIp();
$__rateData = getData(FILE_REPORT_RATE);
$__now = time();
$__window = 600; // 10 minutes
$__maxReq = 5;
if (!isset($__rateData[$__ip])) { $__rateData[$__ip] = array(); }
// Drop timestamps older than the window
$__rateData[$__ip] = array_values(array_filter($__rateData[$__ip], function ($t) use ($__now, $__window) {
    return ($__now - $t) < $__window;
}));
if (count($__rateData[$__ip]) >= $__maxReq) {
    http_response_code(429);
    echo json_encode(array('success' => false, 'error' => 'Too many reports from your IP. Please try again later.'));
    saveData(FILE_REPORT_RATE, $__rateData);
    exit;
}
$__rateData[$__ip][] = $__now;
// Cap the file size: keep only last 100 IPs
if (count($__rateData) > 100) {
    $__rateData = array_slice($__rateData, -100, null, true);
}
saveData(FILE_REPORT_RATE, $__rateData);
unset($__ip, $__rateData, $__now, $__window, $__maxReq);

/* ---------- Honeypot field ---------- */
// A hidden "website" field is added to the form. Real users never fill it.
// Bots auto-fill all fields, so if it's non-empty, we silently drop the report.
$honeypot = isset($_POST['website']) ? trim($_POST['website']) : '';
if ($honeypot !== '') {
    // Pretend success so the bot doesn't retry
    echo json_encode(array('success' => true, 'message' => 'Report submitted. Thank you!'));
    exit;
}

/* ---------- Validate input ---------- */
$itemType = isset($_POST['type']) ? trim($_POST['type']) : '';
$itemId   = isset($_POST['id']) ? trim($_POST['id']) : '';
$itemSlug = isset($_POST['slug']) ? trim($_POST['slug']) : '';
$reason   = isset($_POST['reason']) ? trim($_POST['reason']) : 'broken';
$detail   = isset($_POST['detail']) ? trim($_POST['detail']) : '';

// Whitelist type
$validTypes = array('movie', 'anime', 'episode');
if (!in_array($itemType, $validTypes, true)) {
    echo json_encode(array('success' => false, 'error' => 'Invalid report type'));
    exit;
}
// Whitelist reason
$validReasons = array('broken', 'wrong', 'quality', 'other');
if (!in_array($reason, $validReasons, true)) {
    $reason = 'other';
}
// Cap detail length
if (mb_strlen($detail, 'UTF-8') > 1000) {
    $detail = mb_substr($detail, 0, 1000, 'UTF-8');
}

if ($itemId === '' && $itemSlug === '') {
    echo json_encode(array('success' => false, 'error' => 'Item identifier required'));
    exit;
}

/* ---------- Save report ---------- */
$logFile = DATA_DIR . '/reports.json';
$existing = array();
if (file_exists($logFile)) {
    $raw = @file_get_contents($logFile);
    if ($raw) {
        $decoded = json_decode($raw, true);
        if (is_array($decoded)) { $existing = $decoded; }
    }
}

$existing[] = array(
    'id'         => 'r' . (count($existing) + 1) . '-' . substr(md5(time() . mt_rand()), 0, 6),
    'type'       => $itemType,
    'item_id'    => $itemId,
    'item_slug'  => $itemSlug,
    'reason'     => $reason,
    'detail'     => $detail,
    'ip'         => clientIp(),
    'user_agent' => isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : '',
    'date'       => date('Y-m-d H:i:s'),
    'resolved'   => false,
);

$saved = @file_put_contents($logFile, json_encode($existing, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));

if ($saved !== false) {
    echo json_encode(array('success' => true, 'message' => 'Report submitted. Thank you!'));
} else {
    echo json_encode(array('success' => false, 'error' => 'Failed to save report'));
}
exit;
